const https = require('https');

const ACCESS_TOKEN = '<REMOVED_SECRET>';
const PROJECT_REF = 'xybbhnteetzoccazcdae';

const sqlScript = `
-- 1. TABELA DE PERFIS DE USUÁRIOS
CREATE TABLE IF NOT EXISTS public.profiles (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT,
  role TEXT DEFAULT 'user',
  status TEXT DEFAULT 'active',
  xp INTEGER DEFAULT 150,
  level INTEGER DEFAULT 1,
  balance NUMERIC(12,2) DEFAULT 1000.00,
  referral_count INTEGER DEFAULT 0,
  interests TEXT DEFAULT 'Tempo,Esportes,Política',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE APOSTAS DA PLATAFORMA
CREATE TABLE IF NOT EXISTS public.bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  creator_name TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  odds_a NUMERIC(5,2) NOT NULL DEFAULT 1.90,
  odds_b NUMERIC(5,2) NOT NULL DEFAULT 1.90,
  status TEXT DEFAULT 'OPEN', -- 'OPEN', 'RESOLVED_A', 'RESOLVED_B', 'CANCELLED'
  is_trending BOOLEAN DEFAULT FALSE,
  total_pool NUMERIC(12,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

-- 3. TABELA DE BILHETES DE APOSTAS DOS USUÁRIOS
CREATE TABLE IF NOT EXISTS public.user_bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
  bet_id BIGINT REFERENCES public.bets(id) ON DELETE CASCADE,
  bet_title TEXT NOT NULL,
  chosen_option TEXT NOT NULL,
  chosen_option_text TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  odds NUMERIC(5,2) NOT NULL,
  potential_win NUMERIC(12,2) NOT NULL,
  status TEXT DEFAULT 'PENDING', -- 'PENDING', 'WON', 'LOST', 'REFUNDED'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABELA DE TRANSAÇÕES FINANCEIRAS
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL,
  description TEXT NOT NULL,
  type TEXT NOT NULL, -- 'DEPOSIT', 'WITHDRAWAL', 'BET_PLACED', 'BET_WON', 'BONUS'
  status TEXT DEFAULT 'COMPLETED', -- 'COMPLETED', 'PENDING', 'FAILED'
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA DE HISTÓRICO DETALHADO DE TRANSAÇÕES
CREATE TABLE IF NOT EXISTS public.transaction_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL,
  type TEXT NOT NULL,
  old_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  new_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABELA DE FEED SOCIAL / POSTAGENS
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
  username TEXT NOT NULL,
  user_level INTEGER NOT NULL DEFAULT 1,
  user_badge TEXT NOT NULL DEFAULT 'Apostador',
  bet_id BIGINT REFERENCES public.bets(id) ON DELETE CASCADE,
  bet_title TEXT NOT NULL,
  chosen_option TEXT NOT NULL,
  chosen_option_text TEXT NOT NULL,
  odds NUMERIC(5,2) NOT NULL,
  comment TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABELA DE NOTIFICAÇÕES E ALERTAS
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR RLS (Row Level Security) E POLÍTICAS DE ACESSO PÚBLICO SEGURO
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all profiles') THEN
    CREATE POLICY "Allow all profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all bets') THEN
    CREATE POLICY "Allow all bets" ON public.bets FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all user_bets') THEN
    CREATE POLICY "Allow all user_bets" ON public.user_bets FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all transactions') THEN
    CREATE POLICY "Allow all transactions" ON public.transactions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all transaction_history') THEN
    CREATE POLICY "Allow all transaction_history" ON public.transaction_history FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all posts') THEN
    CREATE POLICY "Allow all posts" ON public.posts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all notifications') THEN
    CREATE POLICY "Allow all notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
`;

const postData = JSON.stringify({ query: sqlScript });

const req = https.request({
  hostname: 'api.supabase.com',
  path: `/v1/projects/${PROJECT_REF}/database/query`,
  method: 'POST',
  headers: {
    'Authorization': `Bearer ${ACCESS_TOKEN}`,
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
}, (res) => {
  let body = '';
  res.on('data', chunk => body += chunk);
  res.on('end', () => {
    console.log('Status HTTP:', res.statusCode);
    console.log('Resposta Supabase SQL:', body);
  });
});

req.on('error', (e) => {
  console.error('Erro na requisição:', e);
});

req.write(postData);
req.end();
