const https = require('https');

const ACCESS_TOKEN = '<REMOVED_SECRET>';
const PROJECT_REF = 'xybbhnteetzoccazcdae';

const sql = `
CREATE TABLE IF NOT EXISTS public.profiles (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  xp INTEGER DEFAULT 150,
  level INTEGER DEFAULT 1,
  referral_count INTEGER DEFAULT 0,
  interests TEXT DEFAULT 'Tempo,Esportes,Política',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  creator_name TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  odds_a NUMERIC(5,2) NOT NULL,
  odds_b NUMERIC(5,2) NOT NULL,
  status TEXT DEFAULT 'OPEN',
  is_trending BOOLEAN DEFAULT FALSE,
  total_pool NUMERIC(12,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bet_id BIGINT REFERENCES public.bets(id) ON DELETE CASCADE,
  bet_title TEXT NOT NULL,
  chosen_option TEXT NOT NULL,
  chosen_option_text TEXT NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  odds NUMERIC(5,2) NOT NULL,
  potential_win NUMERIC(12,2) NOT NULL,
  status TEXT DEFAULT 'PENDING',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC(12,2) NOT NULL,
  description TEXT NOT NULL,
  type TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  user_level INTEGER NOT NULL,
  user_badge TEXT NOT NULL,
  bet_id BIGINT REFERENCES public.bets(id) ON DELETE CASCADE,
  bet_title TEXT NOT NULL,
  chosen_option TEXT NOT NULL,
  chosen_option_text TEXT NOT NULL,
  odds NUMERIC(5,2) NOT NULL,
  comment TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and add public access policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select profiles') THEN
    CREATE POLICY "Allow public select profiles" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select bets') THEN
    CREATE POLICY "Allow public select bets" ON public.bets FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select user_bets') THEN
    CREATE POLICY "Allow public select user_bets" ON public.user_bets FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select transactions') THEN
    CREATE POLICY "Allow public select transactions" ON public.transactions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select posts') THEN
    CREATE POLICY "Allow public select posts" ON public.posts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public select notifications') THEN
    CREATE POLICY "Allow public select notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
`;

const postData = JSON.stringify({ query: sql });

const req = https.request({
  hostname: 'api.supabase.com',
  path: `/v1/projects/${PROJECT_REF}/database/query`,
  method: 'POST',
  headers: {
    'Authorization': `Bearer ${ACCESS_TOKEN}`,
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
}, (res) => {
  let body = '';
  res.on('data', chunk => body += chunk);
  res.on('end', () => {
    console.log('Status:', res.statusCode);
    console.log('Response:', body);
  });
});

req.on('error', (e) => {
  console.error('Error:', e);
});

req.write(postData);
req.end();
