const https = require('https');

const ACCESS_TOKEN = '<REMOVED_SECRET>';
const PROJECT_REF = 'xybbhnteetzoccazcdae';

const sqlScript = `
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all categories') THEN
    CREATE POLICY "Allow all categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

INSERT INTO public.categories (name) VALUES 
('Tempo'),
('Política'),
('Dia-a-dia'),
('Esportes'),
('Entretenimento'),
('📹 Ao Vivo')
ON CONFLICT (name) DO NOTHING;
`;

const postData = JSON.stringify({ query: sqlScript });

const req = https.request({
  hostname: 'api.supabase.com',
  path: `/v1/projects/${PROJECT_REF}/database/query`,
  method: 'POST',
  headers: {
    'Authorization': `Bearer ${ACCESS_TOKEN}`,
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
}, (res) => {
  let body = '';
  res.on('data', chunk => body += chunk);
  res.on('end', () => {
    console.log('Status HTTP:', res.statusCode);
    console.log('Resposta Supabase SQL:', body);
  });
});

req.on('error', (e) => {
  console.error('Erro na requisição:', e);
});

req.write(postData);
req.end();
